# Build arguments
ARG SOURCE_CODE=.

FROM registry.redhat.io/ubi8/go-toolset:1.21@sha256:742ae6ec1aef3e7faae488c47695fb64964d342aefecf52d23bd9d5e6731d0b6 as builder

## Build args to be used at this step
ARG SOURCE_CODE

## Switch to root as required for some operations
USER root

COPY ${SOURCE_CODE}/go.mod ./
COPY ${SOURCE_CODE}/go.sum ./

RUN go mod download

# Copy the source
COPY ${SOURCE_CODE}/ ./

RUN GO111MODULE=on go build -o /bin/cache_server backend/src/cache/*.go

FROM registry.redhat.io/ubi8/ubi-minimal@sha256:c38cc770631788157f8ea989df65ff30359c9f8af3246fef244b32caed9d5862
WORKDIR /bin


COPY --from=builder /bin/cache_server /bin/cache_server

ENTRYPOINT [ "/bin/cache_server" ]

LABEL com.redhat.component="odh-ml-pipelines-cache-container" \
      name="managed-open-data-hub/odh-ml-pipelines-cache-container-rhel8" \
      git.url="${CI_DATA_SCIENCE_PIPELINES_TEKTON_UPSTREAM_URL}" \
      git.commit="${CI_DATA_SCIENCE_PIPELINES_TEKTON_UPSTREAM_COMMIT}" \
      summary="odh-ml-pipelines-cache" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-ml-pipelines-cache" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      description="odh-ml-pipelines-cache" \
      io.k8s.description="odh-ml-pipelines-cache" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"