# Copyright 2021 The Kubeflow Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Build arguments
ARG SOURCE_CODE=.
ARG TARGETOS=linux
ARG TARGETARCH=amd64
ARG BUILDER_ARCH=multiarch

FROM registry.access.redhat.com/ubi9/go-toolset:1.26.3@sha256:45bd06d392349dfdb09073514cfebcc5082db33301347b51dcae8e5516a89126 AS go-toolset-multiarch
FROM registry.access.redhat.com/ubi9/go-toolset:1.26.3@sha256:3880436381044c6d89c2311f2a7dc8d64224668bf84b43810982b5a9ddd851d0 AS go-toolset-arm64
FROM go-toolset-${BUILDER_ARCH} AS builder

## Build args to be used at this step
ARG SOURCE_CODE
ARG TARGETOS
ARG TARGETARCH

## Switch to root as required for some operations
USER root

RUN dnf upgrade -y && \
    dnf install -y bash && \
    dnf clean all && rm -rf /var/cache/yum

COPY ${SOURCE_CODE}/go.mod ./
COPY ${SOURCE_CODE}/go.sum ./
COPY ${SOURCE_CODE}/kubernetes_platform/go.mod ./kubernetes_platform/go.mod
COPY ${SOURCE_CODE}/api/go.mod ./api/go.mod

RUN GOTOOLCHAIN=local GO111MODULE=on go mod download

# Copy the source
COPY ${SOURCE_CODE}/ ./

RUN GOTOOLCHAIN=local GO111MODULE=on CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
      GOFIPS140=v1.0.0 \
      go build -tags no_openssl -o /bin/controller backend/src/crd/controller/scheduledworkflow/*.go

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.5@sha256:865c6a875328a1174ff7f17599574412edd327aa47812951b9bead902806dc53 AS ubi-minimal-multiarch
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.5@sha256:da229086eb7881bb653e99ace537fc03512bbbfcf14024e7e447b48015d7cc8c AS ubi-minimal-arm64
FROM ubi-minimal-${BUILDER_ARCH} AS runtime-deps
RUN microdnf install -y tzdata.noarch && microdnf clean all

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.5

WORKDIR /bin

COPY --from=builder /bin/controller /bin/controller
COPY --from=runtime-deps /usr/share/zoneinfo /usr/share/zoneinfo

ENV NAMESPACE=""
ENV LOG_LEVEL=info

CMD /bin/controller --logtostderr=true --namespace=${NAMESPACE} --logLevel=${LOG_LEVEL}
