apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-scheduledworkflow
spec:
  template:
    spec:
      containers:
        - name: ml-pipeline-scheduledworkflow
          env:
            # Allow v1 pipelines in the kubeflow CI namespace.
            - name: V1_ALLOWED_NAMESPACES
              value: "kubeflow"
