name: Frontend Tests

on:
  push:
    branches:
      - master
      - main
      - stable
      - 'rhoai-*'
  pull_request:
    branches:
      - master
      - main
      - stable
      - 'rhoai-*'
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
      - '!**/*.md'
      - '!**/OWNERS'
      - 'backend/src/apiserver/config/sample_config.json'

jobs:
  frontend-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Clean npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: cd ./frontend && npm ci

    - name: Run Frontend Tests
      run: cd ./frontend && npm run test:ci

